repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        args: [ --line-length=120, --target-version=py38, --safe ]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [ python ]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [ python ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

      - id: tests
        name: unittest
        entry: python3 -m unittest tests/__main__.py
        language: python
        'types': [ python ]
        pass_filenames: false
        stages: [ commit ]
