repos:
  - repo: local
    hooks:
      # For reformatting code
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        args: [ --line-length=99, --target-version=py38 ]

      # For upgrade python code syntax for newer versions of the language
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [ python ]

      # Tool for automatically reordering python imports
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [ python ]

      # Removes unused imports and unused variables from Python code
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

      # flake config
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]

      # Run python unittest
      - id: tests
        name: pytest
        entry: pytest
        language: python
        types: [ python ]
        pass_filenames: false
        args: [ -v ]
        stages: [ commit ]
